# Generated by Django 4.1.7 on 2023-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
